### PR TITLE
GET counties

### LINKED ISSUE #7: Counties Endpoint
Create an Endpoint that provides a list of counties that can be selected in order to return a full data set.

REST Types: GET

Input Parameters: None

URL: /counties

Returns: JSON list of counties and their ID.

### PR DESCRIPTION
**Pull request by pjhoberman**
Set up GET /counties to return a dict of counties. key is the ID, value is the county name. ID is in a str format as FastAPI converts it to a string anyway, and the test matching the response makes more sense this way.

This branch sets up pytest and tests this endpoint.

This branch also includes a conversion to pip-chill (already combining efforts in single branches, sorry!), and cleans up requirements.txt. This branch also updates the readme re: pip-chill.

One issue I ran into, and this might be how my pycharm is setup, is the module import for `data.counties`. `main.app` runs fine with just `from data.counties import county_list`, but pytest freaks out, claiming `ModuleNotFoundError`. By updating `main.app` to use `from backend.data.counties` everything works, but I feel like I shouldn't need to include `backend` since `main.app` and `data` are both under `backend`. Anyway, let me know if you see a fix or if that's ok.

Closes #7

### CODE REVIEW

**Comment by pjhoberman** [comment]
Actually, hold off on merging - the import issue is causing conflict between pytest and the server.

**Comment by leblowl** [comment]
Hey @pjhoberman, `from backend.data.counties` looks correct to me if you are running `pytest` from the repository root. But if we are planning to have a `backend` and `frontend` directory at the top-level of the repo, where `backend` and `frontend` are basically their own projects, then it doesn't make sense to me to invoke `pytest` from the repository root. I would `cd backend && pytest`... when you do that you should be able to use `from data.counties`.

I believe the Python module import statements depend on the PYTHONPATH and the current directory: https://docs.python.org/3/tutorial/modules.html#the-module-search-path

**Comment by pjhoberman** [comment]
@leblowl Thanks! So when I follow those steps, the server runs fine but pytest then gives me an error about data:

```
Traceback:
tests/test_main.py:2: in <module>
    from backend.main import app, county_list
main.py:2: in <module>
    from data.counties import county_list
E   ModuleNotFoundError: No module named 'data'
```

**Comment by leblowl** [comment]
@pjhoberman I got it working in this branch: https://github.com/codefordenver/energy-assistance-dashboard/pull/15

**Comment by leblowl** [comment]
@pjhoberman Did that also fix it on your local machine?

**Comment by pjhoberman** [comment]
@leblowl Yep! I think deleting the cache was the key. Running in circles over here!

**Comment by pjhoberman** [comment]
@jberns Sorry for all that! Ready for review.

**Pull request merged**
